# MongoDB Atlas URI (con base de datos "inventario")
spring.data.mongodb.uri=mongodb+srv://eltornillofelizdev:miguelb7610@cluster0.smtxl6y.mongodb.net/inventario?retryWrites=true&w=majority&appName=Cluster0

# JWT configuraci\u00F3n
jwt.secret=EstaEsMiClaveSuperSecretaParaElTornilloFeliz123!
jwt.expiration=3600000
