spring.data.mongodb.uri=mongodb+srv://mipa57125:bHphjtO3EGPjM5WX@cluster0.8hy6flp.mongodb.net/inventario?retryWrites=true&w=majority&appName=Cluster0
<properties>
  <java.version>17</java.version>
  <lombok.version>1.18.28</lombok.version>
</properties>
