spring.data.mongodb.uri=mongodb+srv://mipa57125:bHphjtO3EGPjM5WX@cluster0.8hy6flp.mongodb.net/inventario?retryWrites=true&w=majority&appName=Cluster0

# JWT Secret Key (cambia esto por una clave fuerte y \u00FAnica)
jwt.secret=Estaesmiclaveparaesteproyectoinventarioelcualestamuybonitoyestacompleto
# JWT Expiration Time in milliseconds (ej. 1 hora = 3600000 ms)
jwt.expiration=3600000